### ISSUE TITLE
群里的聊天记录

### ISSUE THREAD

**Issue by xiaohuoni** [umijs/umi-example-monorepo#1]
刚刚不知道这个项目是什么，翻了一下群里的聊天记录，觉得应该把这讨论保留下来。
其中a是三直，b是云谦，c是_(:з」∠)_   （都是微信名字，就是有这个符号的怕，看起来很乱，所以用abc代替）
a:群里有人改造umi router实现monorepo项目么？私聊~基本思路，分散路由，model，service到子package，并暴露路由、菜单，子package可以独立打包、测试，dlll化，主package(umi项目结构)封装基础路由，组合菜单，鉴权，异常处理，util库等。默认umi router配置式路由是基于pages目录的，无法实现，需自定义react-router
b:子模块和主模块重复的依赖有想好怎么处理吗？
a:Yarn workspace应该可以
b:子模块不是独立打包吗？那子模块依赖的 react、dva、antd 等如何处理？
a:可以共享一套dll配置,只要稍微改写下目前umi-dll-plugin应该就能实现
b:umi-plugin-dll 现在不是给 prod 用的，只是用于提速。
c:目前 umi 的 monorepo 支持有点问题
a:目前umi-dll-plugin没有关联版本号，只是匹配文件名相等，确实不太好弄
c:也就是，如果你用 yarn workspace，你会出现找不到自己安装的 react 的问题
c:因为安装在了 workspace 的根的 node_modules 下面
a:
<img width="185" alt="wechatimg75" src="https://user-images.githubusercontent.com/11746742/48612034-c00ffa80-e9c2-11e8-9a28-25c82e92cb03.png">
a:默认af-webpack，js-loader会排除node_modules，这个也需要改写，不过真正麻烦的地方在于路由,umi和路由是强耦合的
c:有个问题，分散路由，model，service到子package
c:什么意思哇，也就是把业务分散到各个 package 吗？
a:就是可以插件化,像java中maven的父子项目
c:我的倾向是，把业务代码都丢到有 umi 依赖的主 package，把业务无关的丢到其他 package
a:https://github.com/spring-projects/spring-framework ，这个就是典型的插件化项目,项目做大了，优势很大
c:比如业务无关的工具库，业务无关的 hooks， component， services……
c:貌似 service 也是业务相关的，但是它很独立
b:分 package 和分目录相比有什么优势？
c:分 package 可以独立出来构建工具,代码量足够小，我们可以渐进式升级
b:子模块构建成 umd 包，然后在主应用里通过 html 的 script 引入？
a:业务复杂的话，目录会比较深，mogorepo的每个子项目因为可以独立拿出来开发，又共享git repo，这是它的优势，另外项目如果固话的话，比如大的项目都是有周期的，之前的迭代基本就固化了，可以打成dll，加速启动
c:每处都是小的package，容易拆分业务,而且 create-react-app 也有计划支持 monorepo
a:这个特别适合中台类项目,不同的中台有独立性，又共享了一些基础特性
b:dll 我觉得还是给 dev 用的，prod 不适用。比如无法做按需，依赖 antd，就需要完整地引入 antd。这样和 externals 的配置没啥差异。
a:我现在做云管平台，要接入不同的云平台，我考虑了多页和单页方案，最后觉得单页的monorepo 用户体验和开发体验是最好的
c:其实我还有个考虑，当第三方库有 bug 时候，我 monorepo 的话，我可以把第三方库带 hotfix 也打包进来,等到我的 fix 的 pr 被 merge 了，再从我的源码中去掉，用官方的

**Comment by xiaohuoni** [comment]
monorepo 对接方式有多种，1) npm 依赖 2) umd 包 。npm 依赖不会存在冗余问题，但 umd 包会有。

**Comment by kuitos** [comment]
可以理解这个分包功能对标的 [microfrontend](https://micro-frontends.org/) 那类目标场景吗？也就是除了不考虑 microfrontend 中的子应用技术无关的需求，目标解决的是诸如 子应用/模块 可以独立 repo、独立团队开发、独立发布的需求吗？

**Comment by LeezQ** [comment]
> 可以理解这个分包功能对标的 [microfrontend](https://micro-frontends.org/) 那类目标场景吗？也就是除了不考虑 microfrontend 中的子应用技术无关的需求，目标解决的是诸如 子应用/模块 可以独立 repo、独立团队开发、独立发布的需求吗？

对的，就是这样的。感觉后面可以做成一个 microfontend 的框架。

**Comment by xiaohuoni** [comment]
项目已有说明：https://github.com/umijs/umi-example-monorepo/blob/master/README.md

**Comment by kuitos** [comment]
> 一个场景是路由的分包，一个站点会包含很多路由，然后一些场景下，比如 @十条 那边的项目，以及 umi ui 的插件化，或者项目太大了想要拆子系统，都会希望能把其中部分路由拆出去，交给其他人维护，然后拆出去的部分提供 umd 包进行对接。
一个场景是组件的分包，比如云凤蝶的场景，云凤蝶包含 page 和 component，page 是架子，由多个 component 组成，但包含哪些 component 是不确定的。所以做 component 的分包可以让 page 按需引用 component。

第二个场景没有疑问。
针对第一个场景，如果指的是 [microfrontend](https://micro-frontends.org/)，那么资源的冗余则几乎不会是主要矛盾(因为不解决业务也能 work)，最大的问题是工程上的(不解决业务不能 work)，举几个例子：
1. 共用一个包导致的子应用与主站的发布周期协调问题
readme 里也提到了，如果共用一个基础包的话
> 版本同步以及升级问题，比如之后要升级 antd@4，那么所有的分包都需要一起升级

主站基础包升级子系统要回归测试、子系统要求升级基础包(碰到 bug) 要配合主站的发布周期，诸如此类问题在共用一个包的情景下一定会层出不穷，工程上粗暴一点的方案通常是子系统独立打包，至于基础包是要 external 还是直接打进去，决定权在于子系统。

2. css 全局作用域的问题
我们可以通过主站的框架为子应用提供相应的 mount/unmount 钩子，但在“现代”web开发以 js 为中心的基础上，如何卸载 css？当然我们有各类 css module 或 css in js 方案可以模拟 scoped style，但是一旦引入了使用了全局 css 方案的类库呢(如 antd)？如果不能正常卸载子应用的 css，如何确保子应用 a1 里的 css 不会影响到子应用 a2？
3. <del>async/dynamic router 的问题</del>
<del>刚翻了一下 umi 基于的 react router 4，所以这个问题也就直接解决了</del>

在系统相对可控的情况下，1、2问题可以通过一些开发约束来解决，但是体量一旦出现膨胀，尤其是业务团队割裂的情况下，问题就会很快的暴露出来(想象一下所有金融云应用都是基于分包方案的...)。 @xiaohuoni @LeezQ 针对这类情况，有什么好的方案吗？

**Comment by Fantasy9527** [comment]
@kuitos  
@LeezQ 
是的,完全可以做成微前端的子模块,
如果你有需要,可以参照我的文章接入微前端:
https://alili.tech/archive/9xuojm75d2a/

**Comment by sorrycc** [comment]
@Fantasy9527 👍，好文。

**Comment by xiaohuoni** [comment]
@Fantasy9527 👍，要不要直接整理一个plugin

**Comment by sorrycc** [comment]
https://github.com/umijs/umi-plugin-single-spa
