### ISSUE TITLE
基于umi 2.4.2给users打umd包，放入main中，目前报错！

### ISSUE THREAD

**Issue by wolfwood1983** [umijs/umi-example-monorepo#6]
集成打包好的umd包到main工程中，启动后报错TypeError: window.SockJS is not a constructor
就是基于umi-example-monorepo项目的代码跑的
![2f816d0d-64bc-4d8e-8b09-bb2d7db52218](https://user-images.githubusercontent.com/37570095/51162260-88dd9d00-18d0-11e9-9d26-2ce2616ce463.png)
![4ddd7d4a-820c-4ab6-9fb5-1f0503d0cd04](https://user-images.githubusercontent.com/37570095/51162269-909d4180-18d0-11e9-97dc-911e5125e7e9.png)

**Comment by wolfwood1983** [comment]
[相关源码.zip](https://github.com/umijs/umi-example-monorepo/files/2758276/default.zip)

**Comment by sorrycc** [comment]
参考 https://github.com/umijs/umi-example-monorepo/commit/0c0e1f7ce4fddf787e0ecb8ee5d08e42155fe514 这个改下，出现那个报错是因为打包了不需要的 model。

**Comment by wolfwood1983** [comment]
十分感谢！这个功能对我们来说很重要！^__^！



wolfwood_yg@sina.com
 
发件人： chencheng (云谦)
发送时间： 2019-01-15 18:37
收件人： umijs/umi-example-monorepo
抄送： wolfwood1983; Author
主题： Re: [umijs/umi-example-monorepo] 基于umi 2.4.2给users打umd包，放入main中，目前报错！ (#6)
参考 0c0e1f7 这个改下，出现那个报错是因为打包了不需要的 model。
